---
# should install the exporter seperately
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

# double check laster!!
- name: Copy local Nginx configuration file
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx Service

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Install Prometheus Nginx Exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter
    state: present

- name: Ensure that both nginx and nginx exporter services are enabled and started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - nginx
    - prometheus-nginx-exporter
