---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Copy local Nginx configuration file
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart Nginx Service

- name: Ensure Nginx service is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Install Prometheus Nginx Node Exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter
    state: present

- name: Start and enable Nginx Exporter service
  ansible.builtin.systemd:
    name: prometheus-nginx-exporter
    state: started
    enabled: yes
