---
- name: Install Nginx
  ansible.builtin.apt:
    name: 
      - nginx
      - prometheus-nginx-exporter
    state: present

# double check laster!!
- name: Copy local Nginx configuration file
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx Service
    - Restart Nginx exporter Service

- meta: flush_handlers

- name: Ensure that both nginx and nginx exporter services are enabled and started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - nginx
    - prometheus-nginx-exporter

