---
- name: Install HaProxy
  ansible.builtin.apt:
    name: haproxy
    state: present

- name: Configure HaProxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart haproxy