---
- name: download InfluxDB GPG keys                 
  ansible.builtin.apt_key:                         
    url: https://repos.influxdata.com/influxdata-archive_compat.key                                   
    state: present                                 
                                                   
- name: add InfluxDB repository                    
  ansible.builtin.apt_repository:                  
    repo: "deb https://repos.influxdata.com/ubuntu stable main"                                       
    state: present                                 
    filename: influxdb                             
                                                   
- name: install InfluxDB and telegraf                        
  ansible.builtin.apt:                             
    name:                                          
    - influxdb=1.8.10-1  
    - telegraf

- name: Configure Telegraf
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: Restart telegraf

- name: Ensure that influx and telegraf are enabled and running
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - influxd
    - telegraf

- name: Install Influx stats exporter
  ansible.builtin.get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_386
    dest: /usr/local/bin/influx_stats_exporter
    mode: 0755

- name: Create service file for influx stats exporter
  ansible.builtin.template:
    src: influx_stats_exporter.service.j2
    dest: /etc/systemd/system/influx_stats_exporter.service
  notify: 
    - Reload systemd
    - Restart influx_stats_exporter

- name: Ensure influx stats exporter is enabled and running
  ansible.builtin.service:
    name: influx_stats_exporter
    state: started
    enabled: true

- name: Create a backup directory
  ansible.builtin.file:
    path: /home/backup/influxdb
    state: directory
    owner: backup
    group: backup
    mode: 0775

- name: copy influxdb backup cron job              
  ansible.builtin.template:                        
    src: influxdb_cron.j2                   
    dest: /etc/cron.d/influxdb-backup              

- name: Add InfluxDB CNAME record                                                                  
  ansible.builtin.include_role:                                                       
    name: dns_record                                                                  
  vars:                                                                               
    dns_record: "influxdb" 