---
- name: Create Grafana directory
  ansible.builtin.file:
    path: "/opt/grafana/provisioning/{{ item }}"
    state: directory
  loop:
    - dashboards
    - datasources

- name: Add grafana.ini
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  notify: 
    - Restart Grafana Container
  no_log: yes

- name: Add default dashboard and datasources
  ansible.builtin.template:
    src: "{{ item }}.yaml.j2"
    dest: "/opt/grafana/provisioning/{{ item }}/default.yaml"
  loop:
    - datasources
    - dashboards

- name: Add dashboards
  ansible.builtin.copy:
    src: "{{ item }}.json"
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}.json"
  loop:
    - main
    - backups
    - mysql
    - syslog

- name: Create Grafana Container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    volumes: /opt/grafana:/etc/grafana
    published_ports: "{{ grafana_port }}:3000"
