---
- name: Create Grafana directory
  ansible.builtin.file:
    path: "/opt/grafana/provisioning/{{ item }}"
    state: directory
  loop:
    - dashboards
    - datasources

- name: Add grafana.ini
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  notify: 
    - Restart Grafana Container
  no_log: yes

- name: Add default dashboard and datasources
  ansible.builtin.template:
    src: "{{ item }}.yaml.j2"
    dest: "/opt/grafana/provisioning/{{ item }}/default.yaml"
  loop:
    - datasources
    - dashboards
  notify: Restart Grafana Container

- name: Add dashboards
  ansible.builtin.copy:
    src: "{{ item }}.json"
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}.json"
  loop:
    - main
    - backups
    - mysql
    - syslog
  notify: Restart Grafana Container

- name: Create Grafana Container
  community.docker.docker_container:
    container_default_behavior: no_defaults  
    name: grafana
    image: grafana/grafana
    user: root
    volumes: /opt/grafana:/etc/grafana
    published_ports: "{{ grafana_port }}:3000"
    restart_policy: always 
  
- name: Add Grafana CNAME record                                                                  
  ansible.builtin.include_role:                                                       
    name: dns_record                                                                  
  vars:                                                                               
    dns_record: "grafana" 