---
- name: Update APT Cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install uWSGI and uWSGI plugin for Python 3
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
    state: present

- name: Create uWSGI directory
  ansible.builtin.file:
    path: /etc/uwsgi/apps-enabled
    state: directory
    owner: agama
    group: agama

- name: Copy local Agama configuration file
  ansible.builtin.template:
    src: templates/agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    group: agama
    mode: '0600'
  become: true
  notify: Restart uWSGI Service

- name: Ensure uWSGI service is started and enabled
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true
