---
# Add init later on
- name: Init
  hosts: all
  roles:
    - init
    
- name: Database Server
  hosts: db_servers
  roles:
    - mysql

- name: Web Server
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx
