---
- name: Init
  hosts: all
  gather_facts: yes
  roles:
    - init
  tags: init

- name: DNS Server
  hosts: dns_servers
  roles:
    - bind
  tags: dns

- name: Configure resolv.conf on all machines
  hosts: all
  roles:
    - resolver
  tags: rslv

- name: Database Server
  hosts: db_servers
  roles:
    - mysql
  tags:
    - db
    - mx

- name: Web Server
  hosts: web_servers
  roles:
    - nginx
    - docker
    - agama
    - haproxy
    - keepalived
  tags:
    - web
    - mx

- name: Install and configure prometheus
  hosts: prometheus
  roles:
    - nginx
    - prometheus
  tags: prome

- name: Install and configure Grafana
  hosts: grafana
  roles: 
    - docker
    - nginx
    - grafana
  tags: graf

- name: Install Influxdb
  hosts: influxdb
  roles:
    - influxdb
  tags: influx

- name: Install agama-client to vm2
  hosts: agama_client
  roles:
    - agama_client
  tags: agama-client
