---
- name: Init
  hosts: all
  roles:
    - init
  tags: init

- name: DNS Server
  hosts: dns_servers
  gather_facts: yes
  roles:
    - bind
  tags: dns

- name: Configure resolv.conf on all machines
  hosts: all
  gather_facts: yes
  roles:
    - resolver
  tags: rslv

- name: Database Server
  hosts: db_servers
  gather_facts: yes
  roles:
    - mysql
  tags: db

- name: Web Server
  hosts: web_servers
  gather_facts: yes
  roles:
    - agama
    - uwsgi
    - nginx
  tags: web

- name: Install and configure prometheus
  hosts: prometheus
  gather_facts: yes
  roles:
    - nginx
    - prometheus
  tags: prome

- name: Install and configure Grafana
  hosts: grafana
  gather_facts: yes
  roles:
    - nginx
    - grafana
  tags: graf