---
- name: Init
  hosts: all
  roles:
    - init

- name: DNS Server
  hosts: dns_servers
  gather_facts: yes
  roles:
    - bind
  tags: d

- name: Database Server
  hosts: db_servers
  roles:
    - mysql

- name: Web Server
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx
