---
- name: Init
  hosts: all
  roles:
    - init

- name: DNS Server
  hosts: dns_servers
  gather_facts: yes
  roles:
    - bind
  tags: d

- name: Database Server
  hosts: db_servers
  gather_facts: yes
  tags: db
  roles:
    - mysql

- name: Configure DNS
  hosts: db_servers:web_servers
  roles:
    - dns

- name: Web Server
  hosts: web_servers
  gather_facts: yes
  roles:
    - agama
    - uwsgi
    - nginx
