{
 "title": "Backups",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Time since last successful backup InfluxDB Telegraf",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"7uu13\", service=\"influxdb\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Time since last successful backup MySql",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"7uu13\", service=\"mysql\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Influx full backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"7uu13\", service=\"influxdb\", type=\"full\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySql full backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"7uu13\", service=\"mysql\", type=\"full\"}",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}