{
 "title": "MySQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 22, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "mysql_global_variables_server_id",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "mysql_global_variables_read_only",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replica I/O thread",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "master: {{master_host}} / replica: {{instance}}"
    }
   ]
  },
  {
   "title": "Replica SQL thread",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "master: {{master_host}} / replica: {{instance}}"
    }
   ]
  },
  {
   "title": "MySQL: SELECT queries per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "increase(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}