---
- name: Restart Bind9 Service
  ansible.builtin.systemd:
    name: bind9
    state: restarted

- name: Reload rncd
  ansible.builtin.command: rndc reload

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart Bind9 Exporter
  ansible.builtin.systemd:
    name: pormetheus-bind-exporter
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes