---
- name: Update APT Cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install MySql
  ansible.builtin.apt:
    name:
      - mysql-server
      - python3-pymysql
    state: present

- name: Override Default Bind-Addr
  ansible.builtin.copy:
    src: /home/johan/Documents/school/taltech/programming/it-infra/ica0002/roles/mysql/files/override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart MySql service

- name: Ensure Mysql service is started and enabled
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Create a new database with name 'agama'
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create a new user with name 'agama'
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock