---
- name: Update APT Cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install MySql
  ansible.builtin.apt:
    name:
      - mysql-server
      - python3-pymysql
      - prometheus-mysqld-exporter
    state: present

- name: Override Default Bind-Addr
  ansible.builtin.copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart MySql service

- meta: flush_handlers

- name: Create a new database with name 'agama'
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create a new user with name 'agama'
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create a new user with name 'exporter'
  community.mysql.mysql_user:
    name: exporter
    password: "{{ exporter_password }}"
    priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Configure my.cnf 
  ansible.builtin.template:
    #mode: 0400
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    #owner: prometheus
  no_log: true
  #notify:

- name: Ensure Mysql exporter service is started and enabled
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - mysql
    - prometheus-mysqld-exporter