---
- name: Gather facts
  ansible.builtin.setup:

- name: Stop and Disable systemd-resolevd
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Configure resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
