---
- name: Restart haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart haproxy exporter
  ansible.builtin.service: 
    name: prometheus-haproxy-exporter
    state: restarted
    enabled: yes