---
- name: Install Prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present

- name: Configure Prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Restart Prometheus

- name: Ensure Prometheus service is started and enabled
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true

- name: Configure /etc/default for prometheus
  ansible.builtin.template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify: Restart Prometheus
