---
- name: Install fping
  ansible.builtin.apt:
    name: fping
    state: present

- name: Create user agama-client
  ansible.builtin.user:
    name: agama-client
    system: yes

- name: Download agama-client configuration
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/romankuchin/ica0002-2024/refs/heads/main/08-logging/08-files/agama-client
    dest: /usr/local/bin/
    mode: 0755

- name: Create service file for agama-client
  ansible.builtin.template:
    src: agama-client.service.j2
    dest: /etc/systemd/system/agama-client.service
  notify:
    - reload system daemon
    - Restart agama-client

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure /etc/agama-client directory exists
  ansible.builtin.file:
    path: /etc/agama-client
    state: directory
    owner: agama-client
    group: agama-client

- name: Add agama-client configuration file
  ansible.builtin.template:
    src: agama-client.conf.j2
    dest: /etc/agama-client/agama-client.conf
  notify: Restart agama-client

- name: Ensure agama_client service is started and enabled
  ansible.builtin.service:
    name: agama-client.service
    state: started
    enabled: true

