---
- name: Restart MySql service
  ansible.builtin.systemd:
    name: mysql
    state: restarted

- name: Restart MySql Node Exporter
  ansible.builtin.systemd:
    name: prometheus-mysqld-exporter
    state: restarted

- name: Reset MySQL source
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - resetprimary
  when: inventory_hostname == mysql_host

- name: Reset MySQL replica
  ansible.builtin.mysql_replication:
    mode: "{{ item }}"
    primary_host: "{{ mysql_host }}"
    primary_user: "{{ replication_user }}"
    primary_password: "{{ replication_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - changeprimary
    - resetreplica
    - startreplica
  when: inventory_hostname != mysql_host
