---
- name: Restart MySql service
  ansible.builtin.systemd:
    name: mysql
    state: restarted

- name: Restart Prometheus Node Exporter
  ansible.builtin.systemd:
    name: prometheus-mysqld-exporter
    state: restarted
