---
#- name: Gather facts
#  ansible.builtin.setup:

- name: Update APT Cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install bind9
  ansible.builtin.apt:
    name: bind9
    state: present

- name: Configure DNS forwarders
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart Bind9 Service

- name: Configure DNS Master Zone
  ansible.builtin.template:
    src: db.lockbox.sec.j2
    dest: /var/cache/bind/db.{{ domain_name }}
  notify: Reload rncd

- name: Ensure bind9 service is started and enabled
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true

