---
- name: Update APT Cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install nvim
  ansible.builtin.apt:
    name: neovim
    state: present

- name: Add user named Juri
  ansible.builtin.user:
    name: juri
    shell: /bin/bash

- name: Add user named Roman
  ansible.builtin.user:
    name: roman
    shell: /bin/bash

- name: Add ssh key for user Juri
  ansible.posix.authorized_key:
    user: juri
    state: present
    key: https://github.com/hudolejev.keys

- name: Add ssh key for user Roman
  ansible.posix.authorized_key:
    user: roman
    state: present
    key: https://github.com/romankuchin.keys

- name: install Nginx node exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Configure rsyslog
  ansible.builtin.template:
    src: 50-telegraf.conf.j2
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify: Restart rsyslog

- name: Ensure influx and telegraf are enabled and running
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - prometheus-node-exporter
    - rsyslog
