---
- name: Update APT Cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install nvim
  ansible.builtin.apt:
    name: neovim
    state: present

- name: Add user named Juri
  ansible.builtin.user:
    name: juri
    shell: /bin/bash

- name: Add user named Roman
  ansible.builtin.user:
    name: roman
    shell: /bin/bash

- name: Add ssh key for user Juri
  ansible.posix.authorized_key:
    user: juri
    state: present
    key: https://github.com/hudolejev.keys

- name: Add ssh key for user Roman
  ansible.posix.authorized_key:
    user: roman
    state: present
    key: https://github.com/romankuchin.keys

- name: install Nginx node exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Configure rsyslog
  ansible.builtin.template:
    src: 50-telegraf.conf.j2
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify: Restart rsyslog

- name: Ensure influx and telegraf are enabled and running
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - prometheus-node-exporter
    - rsyslog

- name: Add user named backup
  ansible.builtin.user:
    name: backup
    shell: /bin/bash
    home: /home/backup
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Configure known_hosts file
  ansible.builtin.template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup

- name: Create a restore directory
  ansible.builtin.file:
    path: /home/backup/restore
    state: directory
    owner: backup
    group: root

- name: Install duplicity
  ansible.builtin.apt:
    name: duplicity
    state: present
